@startuml a
!define RECTANGLE class

!theme spacelab



node "Android Device" as user_device {
  agent "Android Device" as web
  agent "Local Laptop" as laptop
}

node "Backend Server" as backend {
  agent "Backend Server" as backendserver
}


web .up.> laptop: HTTP
laptop .up.> backend: HTTP through tunnel
@enduml